version: '2.1'
services:
  
  databasemysql:
    image: mysql:latest
    restart: always 
    environment:
      - MYSQL_DATABASE=HELLOMY
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345789!6mJb
      - MYSQL_ROOT_PASSWORD=123457891012!6mJb
    ports:
        - "3306:3306"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 30s
        timeout: 10s
        retries: 5       
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./sitehome:/app

    #environment:
    #  - DATABASE_URL=mysql+pymysql://user:12345789!6mJb@databasemysql:3306/HELLOMY
    depends_on:
      databasemysql:
        condition: service_healthy
    #command: sh -c "/wait && uvicorn app:app --host 0.0.0.0 --port 8080 --reload "
    #  #
    #environment:
    # - WAIT_HOSTS=databasemysql:3306
    # - WAIT_HOSTS_TIMEOUT=300
    # - WAIT_SLEEP_INTERVAL=30
    # 
    #  - WAIT_HOST_CONNECT_TIMEOUT=30
